"""Generate Modules/Core/InputsDump.mqh from the input declarations in Claude.mq5.

InputsDump() returns every input as "InpName=value;..." so OnTester can log the exact inputs of each pass
(inputs.csv) - the tester's forward-results XML can show wrong parameter values (Round 35).
Run after adding / removing inputs:   python Research/gen_inputs_dump.py   (then recompile Claude.mq5)
make_set.py warns when the dump is out of date.
"""
import re
from pathlib import Path

EA = Path(__file__).resolve().parent.parent
SRC = EA / "Claude.mq5"
OUT = EA / "Modules" / "Core" / "InputsDump.mqh"


def inputs():
    return re.findall(r"^\s*input\s+(\w+)\s+(\w+)\s*=", SRC.read_text(encoding="utf-8"), re.M)


def main():
    lines = []
    for typ, name in inputs():
        if typ == "bool":
            expr = f'({name} ? "true" : "false")'
        elif typ == "double":
            expr = f"DoubleToString({name}, 8)"
        elif typ == "string":
            expr = f"DumpText({name})"
        else:                                             # int, long, ulong, enums, color, datetime
            expr = f"IntegerToString((long){name})"
        lines.append(f'   s += "{name}=" + {expr} + ";";')
    body = "\n".join(lines)
    OUT.write_text(f"""//+------------------------------------------------------------------+
//|                                                  InputsDump.mqh |
//|  GENERATED by Research/gen_inputs_dump.py - do not edit.         |
//|  Every EA input as "InpName=value;" for inputs.csv (OnTester).   |
//|  Include after the input declarations. Regenerate when inputs    |
//|  change.                                                         |
//+------------------------------------------------------------------+
#ifndef CLAUDE_INPUTSDUMP_MQH
#define CLAUDE_INPUTSDUMP_MQH

#define INPUTS_DUMP_COUNT {len(lines)}

//--- strings may contain ';' or tabs (symbol overrides, pair settings): keep the dump parseable
string DumpText(const string v)
  {{
   string r = v;
   StringReplace(r, ";", "|");
   StringReplace(r, "\\t", " ");
   return "\\"" + r + "\\"";
  }}

string InputsDump(void)
  {{
   string s = "";
{body}
   return s;
  }}

#endif
//+------------------------------------------------------------------+
""", encoding="utf-8")
    print(f"wrote {OUT} ({len(lines)} inputs)")


if __name__ == "__main__":
    main()
