"""Generate a Strategy Tester .set file from the input defaults in Claude.mq5.

The tester remembers the last-used value of every input (Profiles/Tester/Claude.set),
which silently overrides new defaults in the code. Loading a generated .set file
guarantees each test runs exactly the code defaults plus the optimisation ranges below.

Usage:  python make_set.py <round-name> [NAME=start:step:stop ...]
        e.g. python make_set.py Round1 InpPreset=1:1:9
Writes: MQL5/Profiles/Tester/Claude_<round-name>.set  (Inputs tab -> right-click -> Load)
        Research/sets/Claude_<round-name>.set          (copy kept in the repo)
"""
import datetime
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
EA_DIR = HERE.parent
MQL5_DIR = EA_DIR.parent.parent
EA_FILE = EA_DIR / "Claude.mq5"

# MT5 built-in enum values used by the inputs
BUILTIN = {
    "PERIOD_CURRENT": 0, "PERIOD_M1": 1, "PERIOD_M5": 5, "PERIOD_M15": 15, "PERIOD_M30": 30,
    "PERIOD_H1": 16385, "PERIOD_H2": 16386, "PERIOD_H4": 16388, "PERIOD_H8": 16392,
    "PERIOD_D1": 16408, "PERIOD_W1": 32769, "PERIOD_MN1": 49153,
}


def load_enums():
    """Map enum member name -> int value for every enum defined in the EA's modules."""
    values = dict(BUILTIN)
    for path in EA_DIR.rglob("*.mqh"):
        text = path.read_text(encoding="utf-8", errors="ignore")
        for body in re.findall(r"enum\s+\w+\s*\{(.*?)\}", text, re.S):
            nxt = 0
            for line in body.splitlines():
                line = line.split("//")[0].strip().rstrip(",")
                if not line:
                    continue
                m = re.match(r"(\w+)\s*(?:=\s*(-?\d+))?$", line)
                if not m:
                    continue
                if m.group(2) is not None:
                    nxt = int(m.group(2))
                values[m.group(1)] = nxt
                nxt += 1
    return values


def to_set_value(raw, enums):
    """Return (value, plain) - plain values (strings, colours) take no optimisation range."""
    raw = raw.strip()
    m = re.match(r"C'(\d+),(\d+),(\d+)'", raw)
    if m:
        r, g, b = map(int, m.groups())
        return str(r + g * 256 + b * 65536), True    # colours are written without a range, like strings
    m = re.match(r"D'(\d{4})\.(\d{2})\.(\d{2})(?: (\d{2}):(\d{2}))?'", raw)
    if m:
        y, mo, d, hh, mm = m.groups()
        dt = datetime.datetime(int(y), int(mo), int(d), int(hh or 0), int(mm or 0), tzinfo=datetime.timezone.utc)
        return str(int(dt.timestamp())), False
    if raw.startswith('"'):
        return raw.strip('"'), True
    if raw in enums:
        return str(enums[raw]), False
    return raw, False


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    name = sys.argv[1]
    ranges = {}
    for arg in sys.argv[2:]:
        key, spec = arg.split("=", 1)
        ranges[key] = spec.split(":")

    enums = load_enums()
    lines = [f"; generated by Research/make_set.py for {name} - load via Inputs tab -> Load"]
    for src in EA_FILE.read_text(encoding="utf-8").splitlines():
        g = re.match(r'\s*input\s+group\s+"(.*)"', src)
        if g:
            lines.append(f"; {g.group(1)}")
            continue
        m = re.match(r"\s*input\s+\w+\s+(\w+)\s*=\s*(.+?);", src)
        if not m:
            continue
        var, raw = m.groups()
        value, plain = to_set_value(raw, enums)
        if plain:
            lines.append(f"{var}={value}")
        elif var in ranges:
            start, step, stop = (to_set_value(v, enums)[0] for v in ranges[var])
            lines.append(f"{var}={value}||{start}||{step}||{stop}||Y")
        else:
            lines.append(f"{var}={value}||{value}||1||{value}||N")

    missing = set(ranges) - {l.split("=")[0] for l in lines}
    if missing:
        sys.exit(f"unknown inputs: {', '.join(sorted(missing))}")

    content = "\r\n".join(lines) + "\r\n"
    targets = [MQL5_DIR / "Profiles" / "Tester" / f"Claude_{name}.set", HERE / "sets" / f"Claude_{name}.set"]
    for t in targets:
        t.parent.mkdir(parents=True, exist_ok=True)
        t.write_bytes(b"\xff\xfe" + content.encode("utf-16-le"))   # UTF-16 LE with BOM, as MT5 writes
        print("wrote", t)


if __name__ == "__main__":
    main()
